name: TEST

on:
  push:

jobs:
  release:
    if: ${{ github.ref##*/ == 'main' }}
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME = ${GITHUB_REF##*/}
    steps:
      - run: echo "${BRANCH_NAME}"