name: TEST

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$branch_name $TAG"
        env:
          branch_name: ${{GITHUB_REF##*/}}
          TAG: ${(git describe --tags $(git rev-list --tags --max-count=1))}
