name: TEST

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG: $(git describe --tags $(git rev-list --tags --max-count=1))
      BRAMCH_NAME: ${GITHUB_REF##*/}
    steps:
      - run: echo "$BRAMCH_NAME $TAG"
