name: TEST

on:
  push:

env:
  TAG: $(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo 'v1.0.0')
  BRAMCH_NAME: ${GITHUB_REF##*/}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print 1
        run: |
          echo "${{ env.BRAMCH_NAME }} ${{ env.TAG }}"
          echo "${{ github.head_ref }}"
      - name: Print 3
        run: |
          echo "GITHUB_WORKFLOW:$GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME:$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
          echo "GITHUB_SHA:$GITHUB_SHA"
          echo "GITHUB_REF:$GITHUB_REF"
          echo "GITHUB_HEAD_REF:$GITHUB_HEAD_REF"
