name: TEST

on:
  push:

env:
  TAG: $(git describe --tags $(git rev-list --tags --max-count=1))
  BRAMCH_NAME: ${GITHUB_REF##*/}
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.BRAMCH_NAME }} ${{ env.TAG }}"
